export const APP_COPY = {
  shell: {
    workspace: "Workspace",
    configuration: "Configuration",
    authenticatedUser: "Local user",
    noEmail: "no-email",
    chat: "Chat",
    menu: "Menu",
    send: "Send",
    thinking: "Thinking...",
  },
  emptyState: {
    onboardingTitle: "Create a graph",
    emptyTitle: "This graph is empty",
    onboardingBody: "Create your first subject graph to start building a real learning trajectory.",
    emptyBody: "Add your first nodes here and start from real structure instead of an empty canvas.",
    createGraph: "Create graph",
  },
  topic: {
    eyebrow: "Topic",
    closeTopic: "Close topic",
    description: "Description",
    noDescription: "No description yet.",
    foundationPath: "Path from foundation",
    resources: "Resources",
    blocked: "blocked",
    blockedResource: "Unsafe resource URL blocked.",
    noResources: "No resources yet.",
    addResource: "Add resource",
    artifacts: "Artifacts",
    noArtifacts: "No artifacts yet.",
    addArtifact: "Add artifact",
    noArtifactBody: "No body.",
    closure: "Closure",
    allClosed: "All prerequisite topics below this node are already closed.",
    blockedCount: (count: number) => `${count} prerequisite topics still need closure.`,
  },
  settings: {
    workspaceConfiguration: "Workspace configuration",
  },
  errors: {
    loadWorkspace: "Failed to load workspace",
    loadChat: "Failed to load chat",
    loadChatSessions: "Failed to load chat sessions",
    loadAssessment: "Failed to load assessment",
    loadHistory: "Failed to load history",
    createGraph: "Failed to create graph",
    renameGraph: "Failed to rename graph",
    saveGraphLayout: "Failed to save graph layout",
    importGraph: "Failed to import graph",
    exportGraph: "Failed to export graph",
    updateConfig: "Failed to update config",
    applyProposal: "Failed to apply proposal",
    syncAppliedProposal: "Proposal applied, but the chat thread could not refresh. Reload the thread if the Applied badge is missing.",
    startQuiz: "Failed to start quiz",
    submitQuiz: "Failed to submit quiz",
    rollbackSnapshot: "Failed to rollback snapshot",
    deleteGraph: "Delete failed",
    deleteSession: "Session delete failed",
  },
  sidebar: {
    closeSidebar: "Close sidebar",
    openSidebar: "Open sidebar",
    openChat: "Open chat",
    documentation: "Documentation",
    logs: "Logs",
    graphTitle: "Graph title",
    saveGraphTitle: "Save graph title",
    renameGraph: (title: string) => `Rename ${title}`,
    exportGraph: (title: string) => `Export ${title}`,
    deleteGraph: (title: string) => `Delete ${title}`,
  },
  graphStats: {
    snapshot: (id: number) => `Snapshot ${id}`,
    saving: "Saving",
    newGraph: "+ New",
    topics: "Topics",
    complete: "Complete",
    closed: "Closed",
    review: "Review",
    saveLayout: "Save layout",
    editGraphLayout: "Edit graph layout",
    mayJitterWhileDragging: "May jitter while dragging",
    cancelLayoutEdit: "Cancel layout edit",
    centerGraph: "Center graph",
  },
  closure: {
    latestQuiz: (score: number) => `Latest quiz ${score.toFixed(0)}%`,
    passed: "Passed",
    failed: "Failed",
    failedCount: (count: number) => `×${count} failed`,
    blockedBy: "Blocked by:",
    closePrerequisitesFirst: "Close prerequisites first",
    generatingQuiz: "Generating...",
    startClosureQuiz: "Start closure quiz",
    markAsFinished: "Mark as finished",
    markingAsFinished: "Marking...",
  },
  sessions: {
    general: "General",
    deleteSession: "Delete session",
    deleteSessionAria: (title: string) => `Delete ${title}`,
    fallbackSessionTitle: "this session",
    learnTopic: (title: string) => `+ Learn ${title}`,
    helloTitle: "Hello!",
    helloCopy: "Ask for help, paste topics, or describe a target.",
    fallbackUsed: "Fallback",
    proposalApplied: "Proposal applied",
    addProposalToGraph: "Add proposal to graph",
    applied: "Applied",
    learningSession: "Learning session",
    focusedOn: (title: string) => `Focused on ${title}`,
    noGraphSelected: "No graph selected",
    groundingToggle: "Toggle web grounding for this request",
    composerPlaceholder: "Ask for help, paste topics, or describe a target.",
  },
  settingsPanel: {
    closeSettings: "Close settings",
    aiBehavior: "AI behavior",
    thinking: "Thinking",
    thinkingLead: "Higher modes let the planner generate more structure per request.",
    memory: "Agent memory",
    memoryLead: "Choose how much recent history and which context blocks the orchestrator sees before making a decision.",
    memoryHistoryLimit: "Recent history messages",
    memoryGraphContext: "Include graph context",
    memoryProgressContext: "Include learner progress",
    memoryQuizContext: "Include quiz history",
    memoryFrontierContext: "Include learning frontier",
    memorySelectedTopicContext: "Include selected-topic context",
    personaRules: "Persona rules",
    personaPlaceholder: "Examples: be concise, be strict about study plans, avoid vague reassurance, focus on concrete next steps.",
    idleGraphMotion: "Idle graph motion",
    idleGraphMotionHelp: "Disables the ambient breathing motion. Generation and new topic placement stay unchanged.",
    debugMode: "Debug mode",
    debugModeHelp: "Enables local capture for frontend errors, API requests, and backend errors. When enabled, Logs appears in the sidebar.",
    appearance: "Appearance",
    theme: "Theme",
    themeHelp: "Use Midnight for the original graph mood or Paper for a brighter workspace that is easier to scan in daylight.",
    themeDark: "Midnight",
    themeDarkHelp: "Dark graph canvas with high-contrast overlays.",
    themeLight: "Paper",
    themeLightHelp: "Warm light workspace with darker graph marks and softer contrast.",
    save: "Save",
    saving: "Saving...",
    snapshots: "Snapshots",
    refreshing: "Refreshing...",
    refresh: "Refresh",
    snapshotLabel: (id: number) => `Snapshot ${id}`,
    current: "Current",
    rollback: "Rollback",
    noSnapshots: "No snapshots yet.",
    closureQuiz: "Closure quiz",
    assessmentThreshold: "Assessment threshold",
    enableClosureTests: "Enable closure tests",
    enableClosureTestsHelp: "If disabled, the quiz button becomes Mark as finished and closes the topic without generating questions.",
    questionsPerQuiz: "Questions per quiz",
    correctAnswersRequired: "Correct answers required",
    closureRule: (correct: number, total: number) => `A topic closes after ${correct} correct answers out of ${total}.`,
    logsTitle: "Logs",
    logsSubtitle: "Local stream for frontend, API, and backend errors.",
    logsFile: "Log file",
    logsFrontend: "Frontend",
    logsApi: "API",
    logsServer: "Server",
    logsEmpty: "Nothing yet.",
    logsClose: "Close logs",
  },
  dialogs: {
    createGraphTitle: "Create graph",
    createGraphBody: "Add a new isolated subject graph to this workspace.",
    importGraphTitle: "Import graph from disk",
    importGraphBody: "Load a local MapMind graph package and choose how much personal state to keep.",
    exportGraphTitle: "Export graph",
    exportGraphBody: "Save this graph as a reusable local package.",
    creating: "Creating...",
    createGraph: "Create graph",
    importFromDisk: "Import from disk",
    chooseFile: "Choose file",
    noFileChosen: "No file chosen yet.",
    importGraph: "Import graph",
    importingGraph: "Importing...",
    exportGraph: "Export graph",
    exportingGraph: "Exporting...",
    createGraphAria: "Close create graph dialog",
    graphTitle: "Title",
    graphTitlePlaceholder: "Computer Engineering",
    addResourceTitle: "Add resource",
    addResourceBody: "Paste a link and it will appear in the topic right away after saving.",
    resourceUrl: "Link",
    resourceUrlPlaceholder: "https://example.com/article",
    saveResource: "Save resource",
    addArtifactTitle: "Add artifact",
    addArtifactBody: "Add a short title and the artifact text itself.",
    artifactTitle: "Title",
    artifactTitlePlaceholder: "Topic notes",
    artifactBodyLabel: "Text",
    artifactBodyPlaceholder: "Short note, formula, takeaway, or plan...",
    saveArtifact: "Save artifact",
    exportTitlePlaceholder: "Mathematics starter kit",
    importTitlePlaceholder: "Imported graph",
    subject: "Subject",
    subjectPlaceholder: "engineering",
    language: "Language",
    languageOptions: { uk: "Ukrainian", ru: "Russian", en: "English" },
    description: "Description",
    descriptionPlaceholder: "First-year CE topics, architecture, circuits...",
    includeOwnProgress: "Include my topic progress",
    importWithProgress: "Import with saved topic progress",
    deleteGraphTitle: "Delete graph",
    deleteGraphBody: "This action cannot be undone.",
    deleteGraphConfirm: (title: string) => `Are you sure you want to delete ${title}? A snapshot will be created first.`,
    deleteChatSessionTitle: "Delete chat session",
    deleteChatSessionBody: "This will remove all messages in this session.",
    deleteChatSessionConfirm: (title: string) => `Are you sure you want to delete ${title}?`,
    cancel: "Cancel",
    delete: "Delete",
  },
  library: {
    nodes: "nodes",
  },
  quiz: {
    title: "Closure quiz",
    selectedTopic: "Selected topic",
    closeQuiz: "Close quiz",
    correctAnswer: (answer: string) => `Correct answer: ${answer}`,
    yourAnswer: (answer: string) => `Your answer: ${answer}`,
    correct: "✓ Correct",
    incorrect: "✗ Incorrect",
    submitting: "Submitting...",
    submit: "Submit quiz",
  },
} as const;

export type AppCopy = typeof APP_COPY;
