export const APP_COPY = {
  shell: {
    workspace: "Clew Workspace",
    workspaceCount: (count: number) => `${count} workspaces`,
    newWorkspace: "New workspace",
    closedTopics: (count: number) => `${count} closed`,
    noTopicsYet: "No topics yet.",
    mobileMenuAria: "Mobile menu",
    configuration: "Configuration",
    authenticatedUser: "Local user",
    noEmail: "no-email",
    chat: "Chat",
    menu: "Menu",
    send: "Send",
    thinking: "Thinking...",
  },
  emptyState: {
    onboardingTitle: "Create a graph",
    emptyTitle: "This graph is empty",
    onboardingBody: "Create your first subject graph to start building a real learning trajectory.",
    emptyBody: "Add your first nodes here and start from real structure instead of an empty canvas.",
    createGraph: "Create graph",
  },
  topic: {
    eyebrow: "Topic",
    closeTopic: "Close topic",
    description: "Description",
    noDescription: "No description yet.",
    foundationPath: "Path from foundation",
    resources: "Resources",
    blocked: "blocked",
    blockedResource: "Unsafe resource URL blocked.",
    noResources: "No resources yet.",
    addResource: "Add resource",
    artifacts: "Artifacts",
    noArtifacts: "No artifacts yet.",
    addArtifact: "Add artifact",
    noArtifactBody: "No body.",
    closure: "Closure",
    allClosed: "All prerequisite topics below this node are already closed.",
    blockedCount: (count: number) => `${count} prerequisite topics still need closure.`,
  },
  settings: {
    workspaceConfiguration: "Workspace configuration",
  },
  errors: {
    loadWorkspace: "Failed to load workspace",
    loadChat: "Failed to load chat",
    loadChatSessions: "Failed to load chat sessions",
    loadAssessment: "Failed to load assessment",
    loadHistory: "Failed to load history",
    createGraph: "Failed to create graph",
    renameGraph: "Failed to rename graph",
    saveGraphLayout: "Failed to save graph layout",
    importGraph: "Failed to import graph",
    exportGraph: "Failed to export graph",
    exportGraphObsidianUnsupported: "Obsidian export needs a browser that supports writing directly into folders.",
    updateConfig: "Failed to update config",
    applyProposal: "Failed to apply proposal",
    syncAppliedProposal: "Proposal applied, but the chat thread could not refresh. Reload the thread if the Applied badge is missing.",
    startQuiz: "Failed to start quiz",
    submitQuiz: "Failed to submit quiz",
    rollbackSnapshot: "Failed to rollback snapshot",
    deleteGraph: "Delete failed",
    deleteSession: "Session delete failed",
  },
  sidebar: {
    closeSidebar: "Close sidebar",
    openSidebar: "Open sidebar",
    openChat: "Open chat",
    documentation: "Documentation",
    logs: "Logs",
    graphTitle: "Graph title",
    saveGraphTitle: "Save graph title",
    renameGraph: (title: string) => `Rename ${title}`,
    exportGraph: (title: string) => `Export ${title}`,
    deleteGraph: (title: string) => `Delete ${title}`,
  },
  graphStats: {
    snapshot: (id: number) => `Snapshot ${id}`,
    saving: "Saving",
    newGraph: "+ New",
    topics: "Topics",
    complete: "Complete",
    closed: "Closed",
    review: "Review",
    saveLayout: "Save layout",
    editGraphLayout: "Edit graph layout",
    mayJitterWhileDragging: "May jitter while dragging",
    cancelLayoutEdit: "Cancel layout edit",
    centerGraph: "Center graph",
    switchToDarkTheme: "Switch to dark theme",
    switchToLightTheme: "Switch to light theme",
    viewportCenteredZoomEnabled: "Viewport-centered zoom enabled",
    pointerFollowZoomEnabled: "Pointer-follow zoom enabled",
  },
  closure: {
    latestQuiz: (score: number) => `Latest quiz ${score.toFixed(0)}%`,
    passed: "Passed",
    failed: "Failed",
    failedCount: (count: number) => `×${count} failed`,
    blockedBy: "Blocked by:",
    closePrerequisitesFirst: "Close prerequisites first",
    generatingQuiz: "Generating...",
    startClosureQuiz: "Start closure quiz",
    markAsFinished: "Mark as finished",
    markingAsFinished: "Marking...",
  },
  sessions: {
    assistantTitle: "Assistant",
    general: "General",
    modelPicker: "Chat model",
    largeGraphModelHint: "Large graph detected. If this keeps failing, try another model or increase the token limits.",
    deleteSession: "Delete session",
    deleteSessionAria: (title: string) => `Delete ${title}`,
    fallbackSessionTitle: "this session",
    learnTopic: (title: string) => `+ Learn ${title}`,
    helloTitle: "Hello!",
    helloCopy: "Ask for help, paste topics, or describe a target.",
    fallbackUsed: "Fallback",
    proposalApplied: "Proposal applied",
    addProposalToGraph: "Add proposal to graph",
    applied: "Applied",
    learningSession: "Learning session",
    focusedOn: (title: string) => `Focused on ${title}`,
    noGraphSelected: "No graph selected",
    groundingToggle: "Toggle web grounding for this request",
    composerPlaceholder: "Ask for help, paste topics, or describe a target.",
  },
  settingsPanel: {
    closeSettings: "Close settings",
    providersEyebrow: "Providers",
    modelProviderTitle: "Model provider",
    modelProviderLead: "Clew runs locally. Choose the active provider and model, then keep credentials in workspace config so the shell stays provider-agnostic.",
    providedByEnv: "Provided by .env",
    providerLabel: "Provider",
    modelLabel: "Model",
    customModelOption: "Custom…",
    customModelId: "Custom model id",
    geminiApiKey: "Gemini API key",
    geminiApiKeyPlaceholder: "AIza...",
    geminiApiKeyEnvNotice: "Gemini key is coming from `.env`, so it has higher priority than workspace config and cannot be changed here.",
    openaiApiKey: "OpenAI API key",
    openaiApiKeyPlaceholder: "sk-...",
    openaiApiKeyEnvNotice: "OpenAI key is coming from `.env`, so it has higher priority than workspace config and cannot be changed here.",
    hideCustomEndpoint: "Hide custom endpoint",
    useCustomEndpoint: "Use custom endpoint",
    openaiEndpointLabel: "OpenAI-compatible endpoint (advanced)",
    openaiEndpointHelp: "You do not need this for the official OpenAI API. Use it only for OpenAI-compatible gateways or local proxies.",
    openaiEndpointEnvNotice: "OpenAI endpoint is coming from `.env`, so it has higher priority than workspace config and cannot be changed here.",
    aiBehavior: "AI behavior",
    thinking: "Thinking",
    thinkingLead: "Higher modes let the planner generate more structure per request.",
    memory: "Agent memory",
    memoryLead: "Choose how much recent history and which context blocks the orchestrator sees before making a decision.",
    memoryHistoryLimit: "Recent history messages",
    memoryGraphContext: "Include graph context",
    memoryProgressContext: "Include learner progress",
    memoryQuizContext: "Include quiz history",
    memoryFrontierContext: "Include learning frontier",
    memorySelectedTopicContext: "Include selected-topic context",
    assistantNickname: "Assistant nickname",
    assistantNicknamePlaceholder: "Optional. Example: Clew, Atlas, Study Partner",
    assistantNicknameHelp: "Keeps the chat header stable and lets the assistant treat this as its workspace nickname in-role.",
    personaRules: "Persona rules",
    personaPlaceholder: "Examples: be concise, be strict about study plans, avoid vague reassurance, focus on concrete next steps.",
    idleGraphMotion: "Idle graph motion",
    idleGraphMotionHelp: "Disables the ambient breathing motion. Generation and new topic placement stay unchanged.",
    edgeLines: "Straight edge lines",
    edgeLinesHelp: "Keeps topic links straight instead of using the loose organic curves.",
    plannerMaxOutputTokens: "Planner max output tokens",
    plannerThinkingBudget: "Planner thinking budget",
    orchestratorMaxOutputTokens: "Chat orchestrator max output tokens",
    quizMaxOutputTokens: "Quiz max output tokens",
    assistantMaxOutputTokens: "Assistant max output tokens",
    debugMode: "Debug mode",
    debugModeHelp: "Enables local capture for frontend errors, API requests, and backend errors. When enabled, Logs appears in the sidebar.",
    appearance: "Appearance",
    theme: "Theme",
    themeHelp: "Use Midnight for the original graph mood or Paper for a brighter workspace that is easier to scan in daylight.",
    themeDark: "Midnight",
    themeDarkHelp: "Dark graph canvas with high-contrast overlays.",
    themeLight: "Paper",
    themeLightHelp: "Warm light workspace with darker graph marks and softer contrast.",
    save: "Save",
    saving: "Saving...",
    snapshots: "Snapshots",
    refreshing: "Refreshing...",
    refresh: "Refresh",
    snapshotLabel: (id: number) => `Snapshot ${id}`,
    current: "Current",
    rollback: "Rollback",
    noSnapshots: "No snapshots yet.",
    closureQuiz: "Closure quiz",
    assessmentThreshold: "Assessment threshold",
    enableClosureTests: "Enable closure tests",
    enableClosureTestsHelp: "If disabled, the quiz button becomes Mark as finished and closes the topic without generating questions.",
    questionsPerQuiz: "Questions per quiz",
    correctAnswersRequired: "Correct answers required",
    closureRule: (correct: number, total: number) => `A topic closes after ${correct} correct answers out of ${total}.`,
    logsTitle: "Logs",
    logsSubtitle: "Local stream for frontend, API, and backend errors.",
    logsFile: "Log file",
    logsFrontend: "Frontend",
    logsApi: "API",
    logsServer: "Server",
    logsEmpty: "Nothing yet.",
    logsDetails: "details",
    logsRequest: "request",
    logsResponse: "response",
    logsStack: "stack",
    logsClose: "Close logs",
  },
  graphText: {
    timeNotSet: "Time not set",
    roadmapLabel: "Roadmap",
    roadmapMlRunway: "ML runway",
    roadmapUsableRunway: "Usable runway",
    roadmapThinRunway: "Thin runway",
    roadmapRationale: "Fallback assessment derived from graph depth.",
    levelAchievedLabel: "Level Achieved",
    levelAchievedFoundationMoving: "Foundation moving",
    levelAchievedNoBaseline: "No baseline",
    levelAchievedRationale: "Fallback assessment derived from closed topics.",
    previewTopics: "Topics",
    previewEdges: "Edges",
    previewNewZones: "New zones",
    previewZoneUpdates: "Zone updates",
    previewMastery: "Mastery",
    previewExpand: "Expand",
    expandGraphAction: "Expand graph",
    ingestTopicsAction: "Ingest topics",
    templateExpandPrompt: "Expand graph toward target: ",
    templateIngestPrompt: "Ingest dirty topic dump: ",
  },
  dialogs: {
    createGraphTitle: "Create graph",
    createGraphBody: "Add a new isolated subject graph to this workspace.",
    importGraphTitle: "Import graph from disk",
    importGraphBody: "Load a local Clew graph package and choose how much personal state to keep.",
    importObsidianTitle: "Import from Obsidian",
    importObsidianBody: "Convert an Obsidian vault into a Clew graph package with validation and import settings before apply.",
    exportGraphTitle: "Export graph",
    exportGraphBody: "Save this graph either as a reusable Clew package or as an Obsidian-ready markdown vault folder.",
    creating: "Creating...",
    createGraph: "Create graph",
    importFromDisk: "Import from disk",
    importFromObsidian: "Import from Obsidian",
    chooseVaultFolder: "Choose vault folder",
    noVaultChosen: "No Obsidian vault chosen yet.",
    chooseFile: "Choose file",
    noFileChosen: "No file chosen yet.",
    importGraph: "Import graph",
    importingGraph: "Importing...",
    importingObsidian: "Importing vault...",
    exportGraph: "Export graph",
    exportingGraph: "Exporting...",
    exportFormat: "Format",
    exportFormatClew: "Clew package",
    exportFormatObsidian: "Obsidian folder",
    obsidianExportOptions: "Obsidian export options",
    obsidianUseFoldersAsZones: "Use folders for primary zones",
    obsidianUseFoldersAsZonesHelp: "Places each topic note inside its primary zone folder when possible.",
    obsidianIncludeDescriptions: "Include topic descriptions",
    obsidianIncludeResources: "Include resources as markdown links",
    obsidianIncludeArtifacts: "Include artifacts as markdown sections",
    obsidianExportHint: "You will pick a destination folder after export. Clew will create one nested folder with the graph title inside it.",
    createGraphAria: "Close create graph dialog",
    graphTitle: "Title",
    graphTitlePlaceholder: "Computer Engineering",
    obsidianVault: "Vault",
    obsidianSubject: "Subject",
    obsidianSubjectPlaceholder: "organise",
    obsidianRelation: "Fallback relation for untyped links",
    obsidianRelationHelp: "Used only when a note link has no explicit Clew relation, for example [[Topic]]::requires or mapmind_relations in frontmatter.",
    obsidianFoldersAsZones: "Use folders as zones",
    obsidianFoldersAsZonesHelp: "Create Clew zones from Obsidian folder paths.",
    obsidianAutofillDescriptions: "Autofill descriptions from note body",
    obsidianAutofillDescriptionsHelp: "Use the first meaningful paragraph in each note as the topic description when possible.",
    obsidianCreateArtifacts: "Create artifacts from note body",
    obsidianCreateArtifactsHelp: "Preserve the cleaned Markdown body as a topic artifact when the note has text.",
    obsidianCreatePlaceholders: "Create placeholder topics for missing links",
    obsidianCreatePlaceholdersHelp: "Turn links to missing notes into placeholder topics instead of dropping them.",
    obsidianPreview: "Preview",
    obsidianIssues: "Validation issues",
    obsidianNoIssues: "No validation issues found. The vault can be imported.",
    obsidianNotesCount: "notes",
    obsidianWarningsCount: "warnings",
    obsidianErrorsCount: "errors",
    obsidianImportReady: (topics: number, edges: number, zones: number) => `${topics} topics · ${edges} edges · ${zones} zones`,
    obsidianImportBlocked: "Fix the validation errors before importing this vault.",
    obsidianNoMarkdown: "No Markdown notes were found in the selected vault.",
    obsidianRelationOptions: {
      requires: "Requires",
      supports: "Supports",
      bridges: "Bridges",
      extends: "Extends",
      reviews: "Reviews",
    },
    addResourceTitle: "Add resource",
    addResourceBody: "Paste a link and it will appear in the topic right away after saving.",
    resourceUrl: "Link",
    resourceUrlPlaceholder: "https://example.com/article",
    saveResource: "Save resource",
    addArtifactTitle: "Add artifact",
    addArtifactBody: "Add a short title and the artifact text itself.",
    artifactTitle: "Title",
    artifactTitlePlaceholder: "Topic notes",
    artifactBodyLabel: "Text",
    artifactBodyPlaceholder: "Short note, formula, takeaway, or plan...",
    saveArtifact: "Save artifact",
    exportTitlePlaceholder: "Mathematics starter kit",
    importTitlePlaceholder: "Imported graph",
    subject: "Subject",
    subjectPlaceholder: "engineering",
    language: "Language",
    languageOptions: { uk: "Ukrainian", ru: "Russian", en: "English" },
    description: "Description",
    descriptionPlaceholder: "First-year CE topics, architecture, circuits...",
    includeOwnProgress: "Include my topic progress",
    importWithProgress: "Import with saved topic progress",
    deleteGraphTitle: "Delete graph",
    deleteGraphBody: "This action cannot be undone.",
    deleteGraphConfirm: (title: string) => `Are you sure you want to delete ${title}? A snapshot will be created first.`,
    deleteChatSessionTitle: "Delete chat session",
    deleteChatSessionBody: "This will remove all messages in this session.",
    deleteChatSessionConfirm: (title: string) => `Are you sure you want to delete ${title}?`,
    cancel: "Cancel",
    delete: "Delete",
  },
  library: {
    nodes: "nodes",
  },
  quiz: {
    title: "Closure quiz",
    selectedTopic: "Selected topic",
    closeQuiz: "Close quiz",
    correctAnswer: (answer: string) => `Correct answer: ${answer}`,
    yourAnswer: (answer: string) => `Your answer: ${answer}`,
    correct: "✓ Correct",
    incorrect: "✗ Incorrect",
    submitting: "Submitting...",
    submit: "Submit quiz",
  },
} as const;

export type AppCopy = typeof APP_COPY;
